name: Run tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # allow manual trigger

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install . --no-deps
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --verbose --show-diff-on-failure

      - name: Test with pytest
        run: |
          pytest -vv

      - name: Run mypy
        run: |
          mypy src/fontra_compile/ tests/
